<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StaffAdmin.aspx.cs" Inherits="UIF.StaffAdmin" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style6
        {
            margin-top: 246px;
        }
    </style>

    <style type="text/css"> 
       div { z-index: 9999; } 
    </style>

</head>
<body bgcolor="Orange">
    <form id="form1" runat="server">
    <div>
    
    </div>

    <asp:Panel ID="pnlBackground" runat="server" BackColor="White"  
        style="z-index: 1; left: -12px; top: 1px; position: absolute; height: 133px; width: 1298px" 
        ViewStateMode="Enabled" BorderColor="Black" BorderStyle="Solid" 
        BorderWidth="3px">
        <asp:Label ID="lblUrbanImpact" runat="server" Font-Bold="True" Font-Size="36pt" 
            style="z-index: 1; left: 354px; top: 24px; position: absolute; height: 62px; width: 547px" 
            Text="Urban Impact Foundation"></asp:Label>
    </asp:Panel>

    <asp:Menu ID="MenuBest" runat="server" BackColor="White" BorderColor="Black"  ForeColor="Black"
        BorderWidth="0px" Orientation="Horizontal" 
        style="z-index: 1; left: 213px; top: 97px; position: absolute; height: 37px; width: 947px" 
        MaximumDynamicDisplayLevels="8" StaticEnableDefaultPopOutImage="False" 
        Height="15px" Font-Bold="True" onmenuitemclick="MenuBest_MenuItemClick">

        <DynamicHoverStyle BackColor="White" Font-Bold="False" 
            Font-Strikeout="False" Height="20px" Font-Italic="False" 
            Font-Size="15pt" />
        <DynamicMenuItemStyle ForeColor="Black" ItemSpacing="4px" 
            VerticalPadding="4px" BackColor="#FFD200" />

        <DynamicMenuStyle BackColor="#FFD200" />
        <DynamicSelectedStyle BackColor="#FFD200" VerticalPadding="4px" Width="40px" />

         <DynamicItemTemplate>
             <%# Eval("Text") %>
        </DynamicItemTemplate>

        <StaticHoverStyle BackColor="#FFD200" Font-Bold="True" Font-Italic="True" 
            Font-Size="15pt" Height="20px" />
        <StaticMenuItemStyle BackColor="White" />
        <StaticMenuStyle BackColor="White" />
        <StaticSelectedStyle BackColor="#FFD200" BorderColor="#FFD200" />
    </asp:Menu>          

    <asp:ImageButton ID="ImageButton1" runat="server"  ImageUrl="~/PerformingArts/Picture1.png"
        style="z-index: 1; left: 25px; top: 13px; position: absolute; height: 114px; width: 172px" 
        onclick="imgButton_Click" />

    <asp:LinkButton ID="LinkButton1" runat="server">LinkButton</asp:LinkButton>

    <asp:Label ID="lblChildrensChoir" runat="server" Font-Bold="False" 
        Font-Size="25pt" 
        style="z-index: 1; left: 470px; top: 151px; position: absolute; height: 49px; width: 453px; text-decoration: underline; font-style: italic;" 
        Text="Staff Info Admin"></asp:Label>

    <asp:GridView ID="gvVolunteerAttendance" runat="server" BackColor="#FFD200" 
        onrowdatabound="gvVolunteerAttendance_RowDataBound"
        style="z-index: 1; left: 60px; top: 314px; position: absolute; height: 159px; width: 306px" 
        BorderColor="Black" BorderStyle="Solid" BorderWidth="2px" 
        onselectedindexchanged="gvVolunteerAttendance_SelectedIndexChanged">
        <AlternatingRowStyle BackColor="Silver" />
        <HeaderStyle BackColor="Black" ForeColor="White" />
    </asp:GridView>


    <asp:GridView ID="gvStaffAdmin" runat="server" AllowSorting="False" 
        OnRowEditing="gvStaffAdmin_RowEditing" BorderStyle="Solid" 
        BorderWidth="4px" CssClass="style6" 
        OnSelectedIndexChanged="gvStaffAdmin_SelectedIndexChanged"
        ShowHeaderWhenEmpty="True" AutoGenerateEditButton="True"  
        OnRowUpdating="gvStaffAdmin_RowUpdating"
        OnRowCancelingEdit="gvStaffAdmin_RowCancelingEdit"
        OnRowDeleting="gvStaffAdmin_RowDeleting"  DataKeyNames="LastName"
        BorderColor="White" 
        AutoGenerateDeleteButton="True" AutoGenerateColumns="False" 
        EnablePersistedSelection="True" 
        BackColor="#FFD200">
        <AlternatingRowStyle BackColor="Silver" />
        <RowStyle Wrap="False" />
        <EditRowStyle Wrap="False" />
        <EmptyDataRowStyle BorderStyle="Solid" />
        <HeaderStyle Font-Bold="True" Font-Overline="False" Font-Size="18pt" 
            Font-Underline="False" BackColor="Black" ForeColor="White" />

        <Columns >  
            <asp:TemplateField HeaderText ="LastName">  
            <ItemTemplate><%#Eval("lastname") %></ItemTemplate>  
            <EditItemTemplate><asp:TextBox ID="textbox1" runat="server" Text='<%#Eval("lastname") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>  

            <asp:TemplateField HeaderText ="FirstName">  
            <ItemTemplate><%#Eval("firstname") %></ItemTemplate>  
            <EditItemTemplate><asp:TextBox ID="textbox2" runat="server" Text='<%#Eval("firstname") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>  

            <asp:TemplateField HeaderText ="Department">  
            <ItemTemplate><%#Eval("department") %></ItemTemplate>  
            <EditItemTemplate><asp:TextBox ID="textbox3" runat="server" Text='<%#Eval("department") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>  

            <asp:TemplateField HeaderText ="ActiveStaffMember">  
            <ItemTemplate><%#Eval("activestaffmember") %></ItemTemplate>  
            <EditItemTemplate><asp:TextBox ID="textbox3" runat="server" Text='<%#Eval("activestaffmember") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>  

            <asp:TemplateField HeaderText ="Role">  
            <ItemTemplate><%#Eval("role") %></ItemTemplate>  
            <EditItemTemplate><asp:TextBox ID="textbox4" runat="server" Text='<%#Eval("role") %>'></asp:TextBox>
            </EditItemTemplate>
            </asp:TemplateField>  

            <asp:TemplateField HeaderText ="Comments">  
            <ItemTemplate><%#Eval("comments") %></ItemTemplate>
            <EditItemTemplate><asp:TextBox ID="textbox5" runat="server" Text='<%#Eval("comments") %>'></asp:TextBox>
            </EditItemTemplate>
            </asp:TemplateField>  

            <asp:TemplateField HeaderText ="UserName">  
            <ItemTemplate> <%#Eval("username")%></ItemTemplate>  
            <EditItemTemplate><asp:TextBox ID="textbox6" runat="server" Text='<%#Eval("username") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>
                  
            <asp:TemplateField HeaderText="PassWord" >  
            <ItemTemplate > <%#Eval("password") %></ItemTemplate>   
            <EditItemTemplate><asp:TextBox ID="textbox7" runat="server" Text='<%#Eval("password") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>  

            <asp:TemplateField HeaderText ="ID" InsertVisible="False" ShowHeader="False">  
            <ItemTemplate><%#Eval("id") %></ItemTemplate>
            <EditItemTemplate><asp:TextBox ID="textbox8" runat="server"  ReadOnly="True" Text='<%#Eval("id") %>'></asp:TextBox></EditItemTemplate>
            </asp:TemplateField>  
        </Columns>  
    </asp:GridView>


    <asp:LinkButton ID="lbhistory" runat="server" onclick="lbhistory_Click" 
        style="z-index: 1; left: 824px; top: 157px; position: absolute">History Report Page</asp:LinkButton>


    <asp:GridView ID="gvUpdateData" runat="server" 
        style="z-index: 1; left: 10px; top: 440px; position: absolute; height: 133px; width: 187px">
    </asp:GridView>


    <asp:TextBox ID="txbLastName" runat="server" BackColor="#FFD200" 
        style="z-index: 1; left: 191px; top: 196px; position: absolute; width: 152px" 
        TabIndex="1" Visible="False"></asp:TextBox>
    <asp:TextBox ID="txbFirstName" runat="server" BackColor="#FFD200" 
        style="z-index: 1; left: 27px; top: 197px; position: absolute; width: 154px" 
        Visible="False"></asp:TextBox>
    <asp:TextBox ID="txbDepartment" runat="server" BackColor="#FFD200" 
        style="z-index: 1; left: 350px; top: 196px; position: absolute" TabIndex="2" 
        Visible="False"></asp:TextBox>
    <asp:TextBox ID="txbRole" runat="server" BackColor="#FFD200" 
        style="z-index: 1; left: 487px; top: 196px; position: absolute" TabIndex="3" 
        Visible="False"></asp:TextBox>
    <asp:TextBox ID="txbComments" runat="server" BackColor="#FFD200" 
        style="z-index: 1; left: 621px; top: 196px; position: absolute" TabIndex="4" 
        Visible="False"></asp:TextBox>
    <asp:TextBox ID="txbUsername" runat="server" BackColor="#FFD200" 
        ontextchanged="txbUsername_TextChanged" 
        style="z-index: 1; left: 755px; top: 195px; position: absolute" TabIndex="5" 
        Visible="False"></asp:TextBox>
    <asp:TextBox ID="txbPassword" runat="server" BackColor="#FFD200" 
        style="z-index: 1; left: 892px; top: 195px; position: absolute" TabIndex="6" 
        Visible="False"></asp:TextBox>
    <asp:CheckBox ID="chbActiveStaffMember" runat="server" BackColor="#FFD200" 
        style="z-index: 1; left: 240px; top: 162px; position: absolute" TabIndex="7" 
        Text="Active Staff Member?" Visible="False" />
    <asp:Button ID="cmbInsertNew" runat="server" onclick="cmbInsertNew_Click" 
        style="z-index: 1; left: 28px; top: 152px; position: absolute; height: 33px; width: 174px" 
        Text="Add New Staff Member" />
    <asp:Label ID="lblFirstName" runat="server" Font-Size="10pt" 
        style="z-index: 1; left: 28px; top: 223px; position: absolute; width: 69px; right: 997px" 
        Text="FirstName" Visible="False"></asp:Label>
    <asp:Label ID="lblLastName" runat="server" Font-Size="10pt" 
        style="z-index: 1; left: 192px; top: 223px; position: absolute; width: 73px" 
        Text="LastName" Visible="False"></asp:Label>
    <asp:Label ID="lblDepartment" runat="server" Font-Size="10pt" 
        style="z-index: 1; left: 351px; top: 221px; position: absolute" 
        Text="Department" Visible="False"></asp:Label>
    <asp:Label ID="lblRole" runat="server" Font-Size="10pt" 
        style="z-index: 1; left: 490px; top: 219px; position: absolute; width: 67px" 
        Text="Role" Visible="False"></asp:Label>
    <asp:Label ID="lblComments" runat="server" Font-Size="10pt" 
        style="z-index: 1; left: 622px; top: 219px; position: absolute; width: 74px" 
        Text="Comments" Visible="False"></asp:Label>
    <asp:Label ID="lblUserName" runat="server" Font-Size="10pt" 
        style="z-index: 1; left: 759px; top: 219px; position: absolute" Text="UserName" 
        Visible="False"></asp:Label>
    <asp:Label ID="lblPassWord" runat="server" Font-Size="10pt" 
        style="z-index: 1; left: 895px; top: 217px; position: absolute; width: 63px" 
        Text="PassWord" Visible="False"></asp:Label>
    </form>
</body>
</html>
